name: ntlm_request
description: Get username from http requests in windows environment to use with ldap and active directory
version: 0.0.1-beta

# homepage: https://www.example.com
repository: https://github.com/GnRSlash/ntlm_request
issue_tracker: https://github.com/GnRSlash/ntlm_request/issues

environment:
  sdk: '>=2.16.0-134.5.beta <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
